version: '3.7'
services:
    web:
        build: .
        restart: always
        logging:
          options:
            max-size: 10m
            max-file: "3"
        network_mode: "host"
        volumes:
          - ./logs/:/app/log/