version: '3.7'
services:
    web:
        platform: linux/amd64 #for mac silicon
        build:
          dockerfile: dockerfile
        restart: always
        logging:
          options:
            max-size: 10m
            max-file: "3"
        # network_mode: "host" we are mapping port no need
        volumes:
          - ./logs/:/app/log/
        ports:
          - "8090:8090"