version: '3.7'
services:
    web:
        build:
          dockerfile: dockerfile
        restart: always
        logging:
          options:
            max-size: 10m
            max-file: "3"
        network_mode: "host"
        volumes:
          - ./logs/:/app/log/
        ports:
          - "8090:8090"